# Generated by Django 3.2 on 2021-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
