# Generated by Django 3.2 on 2021-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0005_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(choices=[('Easy', 0), ('Medium', 1), ('Hard', 2)]),
        ),
    ]
